# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FOSSi Foundation
email: info@fossi-foundation.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fossi-foundation.org" # the base hostname & protocol for your site
twitter_username: fossi-foundation
github_username:  fossi-foundation

# Build settings
markdown: kramdown
